[[project]]
name = "chewingwl"
desc = "A Wayland native input method frontend for the Chewing(Traditional Chinese) library."
tags = ["Wayland", "Rust", "Input Method", "Chewing", "Traditional Chinese"]
[[project.links]]
name = "GitHub"
url = "https://github.com/rano-oss/chewingwl"

[[project]]
name = "wkb"
desc = "A Wayland keyboard descriptions/layouts handling library."
tags = ["Wayland", "Rust", "Linux"]
[[project.links]]
name = "GitHub"
url = "https://github.com/rano-oss/wkb"

[[project]]
name = "libchinese"
desc = "A rewrite of libinyin and libzhuyin in rust, just for fun to test out modern LLM capabilities."
tags = ["Rust", "Chinese", "Library", "Pinyin", "Zhuyin"]
[[project.links]]
name = "GitHub"
url = "https://github.com/rano-oss/libchinese"
